
const action = {
  GET_ALL_COMMENTS_SUCCESSFUL: 'GET_ALL_COMMENTS_SUCCESSFUL',
  GET_ALL_COMMENTS_FAIL: 'GET_ALL_COMMENTS_FAIL',
  NEW_COMMENT_DATA: 'NEW_COMMENT_DATA',
  POST_COMMENT_SUCCESSFUL: 'POST_COMMENT_SUCCESSFUL',
  POST_COMMENT_FAIL: 'POST_COMMENT_FAIL',
};

export default action;
