const ACTION_TYPE = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_REGISTRATION: 'USER_REGISTRATION',
  CHANGE_LOGIN_FIELDS: 'CHANGE_LOGIN_FIELDS',
  GET_USER_INPUT: 'GET_USER_INPUT',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_FAILURE: 'FETCH_ARTICLES_FAILURE',
  LIKEDISLIKE_ARTICLE: 'LIKEDISLIKE_ARTICLE',
  GET_ARTICLE: 'GET_ARTICLE',
  GET_LIKE_STATUS: 'GET_LIKE_STATUS',
  USER_LOGIN: 'USER_LOGIN',
  SHOW_ERROR: 'SHOW_ERROR',
};

export default ACTION_TYPE;
