const ACTION_TYPE = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_REGISTRATION: 'USER_REGISTRATION',
  CHANGE_LOGIN_FIELDS: 'CHANGE_LOGIN_FIELDS',
};

export default ACTION_TYPE;
